Syntax updates based on TS/ES6 guidelines
akiyamaSM/corona-wash-reminder pull request #1
Opened 2020-03-18 23:13 UTC by khofaai

Apply syntax changing based on :

- https://github.com/basarat/typescript-book/blob/master/docs/styleguide/styleguide.md
- https://github.com/airbnb/javascript

and separating translation logic and other configs that shouldn't be hard coded

2020-03-19 18:53 UTC, akiyamaSM requested changes

2020-03-19 18:53 UTC, akiyamaSM commented on src/app/app-routing.module.ts
> +  {
I still like the inline way

2020-03-19 18:53 UTC, akiyamaSM commented on src/app/home/home.page.ts
> +    if(started_at != null) {
Naaaaaaaaaaaaaaaaaaan

2020-03-20 08:42 UTC, khofaai commented on src/app/app-routing.module.ts
> +  {
the inline way has to much throwback, like you add one `,` and the whole line considered as changing, also readability dude !! inline object like doing this in php : 
```
$obj->key = $value; $obj->keyTwo = $valueTwo; $obj->keyThree = $valueThree;
```

2020-03-20 08:58 UTC, khofaai commented on src/app/home/home.page.ts
> +    if(started_at != null) {
you shouldn't do that !!! when you call a function after condition is not like passing values !
duuude readabilityyyy !!

2020-03-20 14:22 UTC, akiyamaSM commented on src/app/app-routing.module.ts
> +  {
I think its more readble the first one

2020-03-20 14:23 UTC, akiyamaSM commented on src/app/home/home.page.ts
> +    if(started_at != null) {
Its the same dude ;)

2020-03-20 14:37 UTC, khofaai commented on src/app/app-routing.module.ts
> +  {
It's one of the most fundamentals for js syntax dude ! it's not about what you think it's about what's right !

2020-03-20 14:38 UTC, khofaai commented on src/app/home/home.page.ts
> +    if(started_at != null) {
noooooo the first is a `inline condition` the second is a `condition` and `statement` there's a biiig difference

2021-09-20 11:19 UTC, closed without merging